kind: Secret
apiVersion: v1
metadata:
  name: example
  annotations:
    vault.mmlt.nl/inject: "true"
    vault.mmlt.nl/inject-path: "secret/data/ns/default/example"
    vault.mmlt.nl/inject-fields: "user=name,pw=password"
